### ISSUE TITLE
ERROR when working with seurat4

### ISSUE THREAD

**Issue by zh-zhang1984** [rnabioco/clustifyrdata#16]
I have a seurat4 object bu found it cannot work with clustifyrdata:
```
> SeuratIntegrate
An object of class Seurat 
30479 features across 191241 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
> res <- clustify(
+     input = SeuratIntegrate,
+     ref_mat = ref_hema_microarray,
+     cluster_col = "integrated_snn_res.0.4"
+ )
found variable genes in SCT slot
Error in object_data.Seurat(s_object, "var.genes", n_genes) : 
  trying to get slot "var.features" from an object of a basic class ("NULL") with no slots
```
Any ideas on how to solve the problem?

**Comment by raysinensis** [comment]
Hi,
I think this is an issue with variable features being stored in the Integrated assay, and clustifyr can't find it.
For now, you can feed the variable features as an argument:
res <- clustify(
     input = SeuratIntegrate,
     ref_mat = ref_hema_microarray,
     cluster_col = "integrated_snn_res.0.4",
     query_genes = VariableFeatures(SeuratIntegrate)
)

Let me know if that works. We will also be updating clustifyr to be smarter with these types of issues as well.
Thanks.

**Comment by zh-zhang1984** [comment]
Yes, that works well for my data; thank you for your help!

**Comment by tanmoy94** [comment]
> alcohol.umap
An object of class Seurat 
11234 features across 2844 samples within 2 assays 
Active assay: integrated (2000 features, 2000 variable features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap

res <- clustify(input = alcohol.umap,ref_mat = cbmc_ref,cluster_col = "seurat_clusters", query_genes = VariableFeatures(alcohol.umap)) 
Error: after subsetting to shared genesquery expression matrix has 0 rows

I have been unable to use clustifyr to create correlation matrix

**Comment by raysinensis** [comment]
Hi @tanmoy94,
We commonly see this error if input and reference genes don't match at all (for instance, if trying to run on human vs mouse genes).
If that is not the issue, could you share the object somehow for us to troubleshoot?
