### ISSUE TITLE
problem installing clustifyrdata

### ISSUE THREAD

**Issue by dinger8** [rnabioco/clustifyrdata#6]
After installing devtools I get the following error after trying to install clustifyrdata

> devtools::install_github("rnabioco/clustifyrdata")

```
Downloading GitHub repo rnabioco/clustifyrdata@master
✓  checking for file ‘/private/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T/RtmpSyRqhZ/remotes163bb3b598210/rnabioco-clustifyrdata-8582364/DESCRIPTION’ ...
─  preparing ‘clustifyrdata’:
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
─  looking to see if a ‘data/datalist’ file should be added
   /Library/Frameworks/R.framework/Resources/bin/build: line 10: 91104 Done                    echo 'tools:::.build_packages()'
        91105 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" --no-restore --slave --args ${args}
Error: Failed to install 'clustifyrdata' from GitHub:
  System command 'R' failed, exit status: 137, stdout + stderr:
E> * checking for file ‘/private/var/folders/fq/_zr6nbj12vlg13hz53xj2vgr0000gn/T/RtmpSyRqhZ/remotes163bb3b598210/rnabioco-clustifyrdata-8582364/DESCRIPTION’ ... OK
E> * preparing ‘clustifyrdata’:
E> * checking DESCRIPTION meta-information ... OK
E> * checking for LF line-endings in source and make files and shell scripts
E> * checking for empty or unneeded directories
E> * looking to see if a ‘data/datalist’ file should be added
E> /Library/Frameworks/R.framework/Resources/bin/build: line 10: 91104 Done                    echo 'tools:::.build_packages()'
E>      91105 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" --no-restore --slave --args ${args}
> 
```

**Comment by jayhesselberth** [comment]
We need to make some updates and hope to have this fixed in a day or two.

**Comment by kriemo** [comment]
Hi @dinger8,
    I am not able to replicate the build error on macOS. Can you provide the output from `sessionInfo()` ? Thanks.

Also, I noticed that there is a reference to a SIGKILL signal (`91105 Killed: 9` ). Be aware that this package is large (~370MB) so it will take awhile to build.

**Comment by dinger8** [comment]
```session_info()
─ Session info ────────────────────────────────────────────────────────────────
 setting  value                       
 version  R version 3.6.3 (2020-02-29)
 os       macOS Catalina 10.15.4      
 system   x86_64, darwin15.6.0        
 ui       RStudio                     
 language (EN)                        
 collate  en_US.UTF-8                 
 ctype    en_US.UTF-8                 
 tz       America/Denver              
 date     2020-04-06                  

─ Packages ────────────────────────────────────────────────────────────────────
 package     * version date       lib source        
 assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
 backports     1.1.6   2020-04-05 [1] CRAN (R 3.6.3)
 callr         3.4.3   2020-03-28 [1] CRAN (R 3.6.1)
 cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.0)
 crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
 curl          4.3     2019-12-02 [1] CRAN (R 3.6.0)
 desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
 devtools    * 2.2.2   2020-02-17 [1] CRAN (R 3.6.0)
 digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.0)
 ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.0)
 fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.0)
 fs            1.4.1   2020-04-04 [1] CRAN (R 3.6.3)
 glue          1.4.0   2020-04-03 [1] CRAN (R 3.6.3)
 magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
 memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
 pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.0)
 pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
 prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.0)
 processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.0)
 ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.0)
 R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.0)
 remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.0)
 rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.0)
 rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
 rstudioapi    0.11    2020-02-07 [1] CRAN (R 3.6.0)
 sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
 testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.0)
 usethis     * 1.5.1   2019-07-04 [1] CRAN (R 3.6.0)
 withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)

[1] /Library/Frameworks/R.framework/Versions/3.6/Resources/library
```

**Comment by dinger8** [comment]
The Killed message always occurs for me when trying to install, after about 2 minutes.

**Comment by kriemo** [comment]
Thanks for the sessionInfo(). I do not see anything wrong with your environment. Could you try another approach? I worry that there may be some issue related to devtools and want to rule this out. 

Could you do these steps and report any errors:

1) Download the github repo as a zip file (green button at https://github.com/rnabioco/clustifyrdata) 
2) Unzip the package
3) run the following R code, with the path updated for your environment:

```r
devtools::install_deps("/path/to/clustifyrdata-master", dependencies = "Imports")
install.packages("/path/to/clustifyrdata-master", repos = NULL, type="source")
```

Thanks for your help debugging this issue.

**Comment by dinger8** [comment]
This is now the error I get:

> devtools::install_deps("~/Desktop/clustifyrdata-master", dependencies = "Imports")
> install.packages("~/Desktop/clustifyrdata-master", repos = NULL, type="source")
* installing *source* package ‘clustifyrdata’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 74055 Done                    echo 'tools:::.install_packages()'
     74056 Killed: 9               | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --slave --args ${args}
Warning in install.packages :
  installation of package ‘/Users/andradingman/Desktop/clustifyrdata-master’ had non-zero exit status

**Comment by dinger8** [comment]
I tried starting with a fresh R session and got this error:
> devtools::install_deps("~/Desktop/clustifyrdata-master", dependencies = "Imports")
> install.packages("~/Desktop/clustifyrdata-master", repos = NULL, type="source")
ERROR: failed to lock directory ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library’ for modifying
Try removing ‘/Library/Frameworks/R.framework/Versions/3.6/Resources/library/00LOCK-clustifyrdata-master’
Warning in install.packages :
  installation of package ‘/Users/andradingman/Desktop/clustifyrdata-master’ had non-zero exit status

**Comment by raysinensis** [comment]
for your latest error, try manually removing the `00LOCK-clustifyrdata-master` file, or use `install.packages("/Desktop/clustifyrdata-master", INSTALL_opts = c('--no-lock'))`

**Comment by dinger8** [comment]
I can't find the 00LOCK-clustifyrdata-master file.  When I try the other command I get this error:
> devtools::install_deps("~/Desktop/clustifyrdata-master", dependencies = "Imports")
> install.packages("~/Desktop/clustifyrdata-master", INSTALL_opts = c('--no-lock'))
Warning in install.packages :
  package ‘~/Desktop/clustifyrdata-master’ is not available (for R version 3.6.3)

**Comment by raysinensis** [comment]
Hmm, that's very strange. None of us has been able to reproduce your problem.
However, this package only contains data, so you can always download the files you need from https://rnabioco.github.io/clustifyrdata/articles/download_refs.html or https://github.com/rnabioco/clustifyrdata/tree/master/data, and then load them into R.

**Comment by raysinensis** [comment]
Hi, we are closing this for now. Please let us know if you still need assistance.
