### ISSUE TITLE
tibble issue when building vignettes

### ISSUE THREAD

**Issue by jayhesselberth** [rnabioco/clustifyrdata#8]
@raysinensis I'm seeing lots of these errors when building vignettes. Are these out of date?

```
   Error: processing vignette 'otherformats.Rmd' failed with diagnostics:
   `df` must be a data frame without row names in `column_to_rownames()`.
   --- failed re-building ‘otherformats.Rmd’
```

**Comment by kriemo** [comment]
FYI, this is likely related to errors from `clustifyr` due to dev dplyr (rnabioco/clustifyr#346) .  I can build this vignette when using CRAN dplyr.
